#!/bin/bash
#===============================================================================
# Winux OS - Environment Variables Setup
# Configures all development environment variables
#===============================================================================

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_done() { echo -e "${GREEN}[DONE]${NC} $1"; }

PROFILE_FILE="$HOME/.profile"
BASHRC_FILE="$HOME/.bashrc"
ZSHRC_FILE="$HOME/.zshrc"

# Create backup
cp "$BASHRC_FILE" "$BASHRC_FILE.bak" 2>/dev/null || true

log_info "Configurando variaveis de ambiente do Winux OS..."

# Write environment configuration
cat >> "$BASHRC_FILE" << 'BASHCONFIG'

#===============================================================================
# Winux OS - Environment Variables
# Auto-generated by winux-env-manager
#===============================================================================

# ----- XDG Directories -----
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

# ----- Local Binaries -----
export PATH="$HOME/.local/bin:$PATH"

# ----- Node.js / NVM -----
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# ----- Java / JDK -----
if [ -d "/usr/lib/jvm/java-21-openjdk-amd64" ]; then
    export JAVA_HOME="/usr/lib/jvm/java-21-openjdk-amd64"
elif [ -d "/usr/lib/jvm/java-17-openjdk-amd64" ]; then
    export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
elif [ -d "/usr/lib/jvm/java-11-openjdk-amd64" ]; then
    export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
fi
[ -n "$JAVA_HOME" ] && export PATH="$JAVA_HOME/bin:$PATH"

# Maven
export MAVEN_HOME="/usr/share/maven"
[ -d "$MAVEN_HOME" ] && export PATH="$MAVEN_HOME/bin:$PATH"

# Gradle
export GRADLE_HOME="/usr/share/gradle"
[ -d "$GRADLE_HOME" ] && export PATH="$GRADLE_HOME/bin:$PATH"

# ----- PHP / Composer -----
export COMPOSER_HOME="$HOME/.config/composer"
[ -d "$COMPOSER_HOME/vendor/bin" ] && export PATH="$COMPOSER_HOME/vendor/bin:$PATH"

# ----- Python -----
export PYTHONDONTWRITEBYTECODE=1
export PYTHONUNBUFFERED=1
export PIPENV_VENV_IN_PROJECT=1
export POETRY_VIRTUALENVS_IN_PROJECT=true
export PIP_USER=1

# Python user packages
[ -d "$HOME/.local/lib/python3/site-packages" ] && export PYTHONPATH="$HOME/.local/lib/python3/site-packages:$PYTHONPATH"

# ----- Rust / Cargo -----
export CARGO_HOME="$HOME/.cargo"
export RUSTUP_HOME="$HOME/.rustup"
[ -f "$CARGO_HOME/env" ] && . "$CARGO_HOME/env"

# ----- Go -----
export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
[ -d "$GOPATH/bin" ] && export PATH="$GOPATH/bin:$PATH"
[ -d "/usr/local/go/bin" ] && export PATH="/usr/local/go/bin:$PATH"

# ----- Android SDK (if installed) -----
if [ -d "$HOME/Android/Sdk" ]; then
    export ANDROID_HOME="$HOME/Android/Sdk"
    export PATH="$ANDROID_HOME/emulator:$PATH"
    export PATH="$ANDROID_HOME/tools:$PATH"
    export PATH="$ANDROID_HOME/tools/bin:$PATH"
    export PATH="$ANDROID_HOME/platform-tools:$PATH"
fi

# ----- Docker -----
export DOCKER_HOST="unix:///var/run/docker.sock"
export COMPOSE_DOCKER_CLI_BUILD=1
export DOCKER_BUILDKIT=1

# ----- Git -----
export GIT_EDITOR="code --wait"

# ----- Editor -----
export EDITOR="nano"
export VISUAL="code"

# ----- Locale -----
export LANG="pt_BR.UTF-8"
export LC_ALL="pt_BR.UTF-8"
export LANGUAGE="pt_BR:en_US"

# ----- Terminal -----
export TERM="xterm-256color"
export COLORTERM="truecolor"

# ----- History -----
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL=ignoreboth:erasedups

# ----- Less -----
export LESS="-R -F -X"
export LESSHISTFILE=-

# ----- Man pages -----
export MANPAGER="less -R"

# ----- GPG -----
export GPG_TTY=$(tty)

# ----- Node.js -----
export NODE_OPTIONS="--max-old-space-size=4096"

# ----- NPM -----
export NPM_CONFIG_PREFIX="$HOME/.npm-global"
[ -d "$NPM_CONFIG_PREFIX/bin" ] && export PATH="$NPM_CONFIG_PREFIX/bin:$PATH"

#===============================================================================
# Development Aliases
#===============================================================================

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# List
alias ll='ls -la'
alias la='ls -A'
alias l='ls -CF'

# Git shortcuts
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline'
alias gd='git diff'

# Docker shortcuts
alias d='docker'
alias dc='docker-compose'
alias dps='docker ps'
alias dex='docker exec -it'

# Development
alias py='python3'
alias pip='pip3'
alias serve='python3 -m http.server'
alias json='python3 -m json.tool'

# System
alias update='sudo apt update && sudo apt upgrade -y'
alias install='sudo apt install'
alias remove='sudo apt remove'

# Winux
alias winux-dev='bash /etc/winux/scripts/setup-dev-full.sh'
alias winux-env='winux-env-manager'

#===============================================================================
# End of Winux OS Environment Configuration
#===============================================================================
BASHCONFIG

log_done "Variaveis de ambiente configuradas!"
log_info "Execute 'source ~/.bashrc' ou reinicie o terminal para aplicar."
